[theme]
primaryColor="#F63366"
backgroundColor="#ffffff"  # Setting background color to white smoke because it sounds too cool for school
secondaryBackgroundColor="#f5f5f5"
textColor="#262730"
font="sans serif"